# Generated by Django 6.0.2 on 2026-02-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='order',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Порядок'),
        ),
    ]
