# Generated by Django 6.0.2 on 2026-03-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_place_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['visit_date', 'visit_time']},
        ),
        migrations.RemoveField(
            model_name='place',
            name='order',
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#CCCCCC', max_length=7, verbose_name='Колір (HEX)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='trip_covers/', verbose_name='Обкладинка'),
        ),
    ]
