# Generated by Django 6.0.2 on 2026-04-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_place_options_remove_place_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('transport', 'Transport'), ('food', 'Food & Drinks'), ('sightseeing', 'Sightseeing'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('others', 'Others')], default='others', max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('transport', 'Transport'), ('food', 'Food & Drinks'), ('sightseeing', 'Sightseeing'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('others', 'Others')], default='others', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
